---
- name: Pull docker image of the Calculator
  hosts: all
  tasks:
    - name: pull docker image
      docker_image:
        name: anmolbisht/calculator_devops
        source: pull
#       shell: docker pull anmolbisht/calculator_devops

